version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: cybergym_sql
    environment:
      SA_PASSWORD: '0neStrongP4ssword!'
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - cybergym-network
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./CybergymHRS
      dockerfile: Dockerfile
    container_name: cybergym_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=CybergymHRS;User Id=sa;Password=0neStrongP4ssword!;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    networks:
      - cybergym-network

  frontend:
    build:
      context: ./CybergymHRS-frontend/cybergym-hrs
      dockerfile: Dockerfile
    container_name: cybergym_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - cybergym-network
    command: /bin/sh -c "sleep 10 && nginx -g 'daemon off;'"

volumes:
  sql_data:

networks:
  cybergym-network:
    driver: bridge
